version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      # Postgresql veritabanı export edilmek istenirse bu yorum satırı açılabilir
      # - ./db:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coffeedb
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - postgres
      - redis
  cron:
    build:
      context: .
      dockerfile: cron.Dockerfile
    volumes:
      - ./src:/var/www/html
    command: >
      sh -c "cd /var/www/html; while true; do php cron/mails.php; sleep 5; done"
    depends_on:
      - postgres
      - redis
